services:
  nyc-warehouse:
    build: .
    environment:
      TAXI_URL: ${TAXI_URL}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_URL: ${POSTGRES_URL}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./db:/app/db
    networks:
      - nyc-networks
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16-alpine
    container_name: nyc-taxi-warehouse-db
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./db/init:/docker-entrypoint-initdb.d
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - nyc-networks

volumes:
  postgres_data:

networks:
  nyc-networks: